### ISSUE TITLE
2022년 2월 2주차 TODO

### ISSUE THREAD

**Issue by GiDaeHyeon** [OwO-CR/daehyeon#3]
- [ ] BentoML 공부 시작 -> 공식 도큐 활용
- [ ] 깔끔한 파이썬 탄탄한 백엔드
    - [ ] 코드 리팩토링
    - [ ] 보다 깔끔하고 보기 좋고 치밀한 테스트 코드 작성
- [ ] 파이썬 Asyncio를 활용한 비동기 처리 공부 시작
